sonar.projectKey=harshal-chauhan-8140_mern-stack-auth-service-micro
sonar.organization=harshal-chauhan-8140

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,src/migration/**
sonar.qualitygate.wait=true
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.scm.exclusions.disabled=true